@baseUrl = http://localhost:3000

# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
	"username": "admin",
	"password": "admin",
	"first_name": "Max",
	"last_name": "Power"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
	"username": "admin",
	"password": "admin"
}

###

@authToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzcxNzE3NjUsImV4cCI6MTYzNzE3MjA2NX0.S7TzJnNsL_mVCaq3lfTcHtfV7WN5bBimNik1k5Ji1rk'

# @name logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{authToken}}


###

# @name reset
POST {{baseUrl}}/auth/reset/
Content-Type: application/json

{
	"username": "admin",
}

