@baseUrl = http://localhost:3000

# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
	"username": "admin",
	"password": "admin",
	"first_name": "Max",
	"last_name": "Power"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
	"username": "admin",
	"password": "admin"
}
###
@authToken = 
# @name logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{authToken}}

###

# @name refresh
POST {{baseUrl}}/auth/refresh/
Authorization: Bearer {{authToken}}

### 
# @name getAllProducts
GET {{baseUrl}}/api/products/

###
# @name getOneProducts
GET {{baseUrl}}/api/products/61999b1b6e13c8d4dba03c46
